version: "3.9"
services:
    transito-flutter:
        build: .
        working_dir: /app
        container_name: transito-server
        image: us-west1-docker.pkg.dev/transito-8f50c/transito-server/transito-server:latest
        restart: unless-stopped
        env_file:
            - .env

    nginx:
        build: .
        container_name: nginx
        image: us-west1-docker.pkg.dev/transito-8f50c/transito-server/nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot

    certbot:
        build: .
        container_name: certbot
        image: us-west1-docker.pkg.dev/transito-8f50c/transito-server/certbot/certbot:latest
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email transito@tnitish.com -d api.transito.tnitish.com --agree-tos
