version: "3.9"
services:
    transito-flutter:
        build: .
        working_dir: /app
        container_name: transito-server
        image: transito-server:latest us-west1-docker.pkg.dev/transito-8f50c/transito-server:latest
        ports:
            - "8080:8080"
        env_file:
            - .env
