version: "3.9"
services:
    transito-flutter:
        build: .
        working_dir: /app
        container_name: transito-server
        image: us-west1-docker.pkg.dev/transito-8f50c/transito-server/transito-server:latest
        ports:
            - "80:80"
        env_file:
            - .env
