name = "transito-refresh"
main = "src/worker.ts"
workers_dev = false
compatibility_date = "2024-10-05"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [ "0 19 * * SAT" ]

[vars]
BASE_URL = "https://transito-api.tnitish.com"