name = "transito-refresh"
main = "src/index.ts"
workers_dev = false
compatibility_date = "2024-10-05"

[triggers]
crons = [ "0 19 * * SAT" ]

[vars]
BASE_URL = "https://transito-api.tnitish.com"

[observability.logs]
enabled = true