import { z } from "zod"

export const LTABusStopSchema = z.object({
	BusStopCode: z.string(),
	RoadName: z.string(),
	Description: z.string(),
	Latitude: z.number().min(-90).max(90),
	Longitude: z.number().min(-180).max(180),
})

export const LTABusStopResponseSchema = z.object({
	"odata.metadata": z.string(),
	value: z.array(LTABusStopSchema),
})

export const TaggedBusStopSchema = z.object({
	code: z.string().length(5),
	name: z.string(),
	roadName: z.string(),
	latitude: z.number().min(-90).max(90),
	longitude: z.number().min(-180).max(180),
	services: z.array(z.string()),
	searchTags: z.array(z.string()),
})

export const BusStopSchema = TaggedBusStopSchema.omit({ searchTags: true })

export const BusStopJSONSchema = z.object({
	metadata: z.string().datetime({ offset: true }),
	data: z.array(TaggedBusStopSchema),
})

export const NearbyBusStopSchema = z.object({
	busStop: BusStopSchema,
	distanceAway: z.number(),
})

export const BasicBusStopSchema = BusStopSchema.omit({ services: true })

export const abbrMappings: Record<any, string> = {
	"a'space": "aerospace",
	ably: "assembly",
	ac: "academy",
	acad: "academy", // Duplicate, consider removing one
	adm: "administration",
	advent: "adventist",
	aft: "after",
	amk: "ang mo kio",
	apt: "apartment",
	apts: "apartments",
	architect: "architecture",
	assn: "association",
	ave: "avenue",
	b: "bus stop",
	bef: "before",
	bet: "between",
	biz: "business",
	bke: "bukit timah expressway",
	bldg: "building",
	blk: "block",
	blks: "blocks",
	blvd: "boulevard", // Corrected spelling
	br: "branch",
	bros: "brothers",
	bt: "bukit",
	"b-p": "bible-presbyterian",
	"c'wealth": "commonwealth",
	"c&i": "communication and information",
	cano: "canossian",
	cath: "cathedral",
	cc: "community centre",
	cck: "choa chu kang",
	cd: "civil defence",
	cee: "civil and environmental engineering",
	cemy: "cemetery",
	ch: "church",
	checkpt: "checkpoint",
	child: "children",
	chr: "christian",
	cl: "close",
	clubhse: "clubhouse",
	cmty: "community",
	coll: "college",
	comsn: "commission",
	condo: "condominium",
	constrn: "construction",
	corp: "corporation",
	cp: "car park",
	cplx: "complex",
	cres: "crescent",
	ct: "court",
	cte: "central expressway",
	ctr: "centre",
	ctrl: "central",
	devt: "development",
	distripk: "distripark",
	dp: "district police/data processing", //Needs clarification on which is intended
	div: "division",
	dr: "drive",
	drv: "driving",
	e: "elizabeth",
	"e.c.": "east coast",
	eng: "english",
	engrg: "engineering",
	env: "environment",
	est: "estate",
	fab: "fabrication",
	fc: "food centre",
	fty: "factory",
	g: "gate",
	green: "green",
	gdn: "garden",
	gdns: "gardens",
	gen: "general",
	govt: "government",
	gr: "grove",
	grp: "group",
	hme: "home",
	hosp: "hospital",
	hq: "headquarters",
	hse: "house",
	hts: "heights",
	ind: "industrial",
	industries: "industries",
	insp: "inspection",
	inst: "institute",
	instn: "institution",
	int: "interchange",
	intl: "international",
	jc: "junior college",
	jln: "jalan",
	jnr: "junior",
	k: "kaliamman",
	kg: "kampong",
	kje: "kranji expressway",
	kpe: "kallang - paya lebar expressway",
	lib: "library",
	lk: "link",
	log: "logistics",
	lor: "lorong",
	lp: "lamp post",
	lt: "lecture theatre",
	ltd: "limited",
	med: "medical",
	met: "metropolitan",
	meth: "methodist",
	mfg: "manufacturing",
	min: "ministry",
	mjd: "masjid",
	mkt: "market",
	mohd: "mohamed",
	mque: "mosque",
	mscp: "multi storey car park",
	mt: "mount",
	natl: "national",
	"no.": "number",
	npc: "neighbourhood police centre",
	nth: "north",
	off: "office",
	opp: "opposite",
	"p/g": "playground",
	"p/l": "private limited",
	pde: "parade",
	pie: "pan island expressway",
	pk: "park",
	pl: "place",
	plt: "plant",
	po: "post office",
	poly: "polytechnic",
	pr: "primary",
	presby: "presbyterian",
	proc: "processing",
	pt: "point",
	pte: "private",
	"r'ford": "rutherford",
	rd: "road",
	reclam: "reclamation",
	reg: "regional",
	"reh.": "rehabilitation",
	rehab: "rehabilitation", // Duplicate, consider removing one
	rel: "release",
	resvr: "reservoir",
	s: "salvation",
	shibuya: "shibuya",
	singapore: "singapore",
	"s.a.": "singapore association",
	"s/h": "schoolhouse",
	"s'goon": "serangoon",
	"s'pore": "singapore",
	sbst: "sbs transit",
	sch: "school",
	sci: "science",
	sec: "secondary",
	sg: "sungei",
	shop: "shopping",
	sib: "singapore infantry brigade",
	sle: "seletar expressway",
	snr: "senior",
	sq: "square",
	st: "street",
	"st.": "saint",
	sth: "south",
	stn: "station",
	"sub-stn": "substation",
	svc: "service",
	svcs: "services",
	swim: "swimming",
	tec: "technology",
	tech: "technology", // Duplicate, consider removing one
	telecoms: "telecommunications",
	temp: "temporary",
	ter: "terminal",
	ters: "terminals",
	terr: "terrace",
	tg: "tanjong",
	townhse: "townhouse",
	tp: "temple",
	tpe: "tampines expressway",
	trg: "training",
	trspt: "transport",
	twr: "tower",
	twrs: "towers",
	upp: "upper",
	v: "village",
	veh: "vehicle",
	"w'lands": "woodlands",
	warehse: "warehouse",
	wk: "walk",
	wtr: "water",
}

export type LTABusStop = z.infer<typeof LTABusStopSchema>
export type LTABusStopResponse = z.infer<typeof LTABusStopResponseSchema>
export type BusStop = z.infer<typeof BusStopSchema>
export type BusStopJSON = z.infer<typeof BusStopJSONSchema>
export type NearbyBusStop = z.infer<typeof NearbyBusStopSchema>
export type BasicBusStop = z.infer<typeof BasicBusStopSchema>
export type TaggedBusStop = z.infer<typeof TaggedBusStopSchema>
