name: Build and push Transito Server Docker image to Google Cloud Platform

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        permissions:
            contents: "read"
            id-token: "write"

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - id: auth
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCE_SA_KEY }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v1

            - name: Configure Docker Client
              run: gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

            - name: Build and push image to Artifact Registry
              env:
                  LTA_API_KEY: ${{ secrets.LTA_API_KEY }}
                  SECRET: ${{ secrets.JSON_SECRET }}
              run: |
                  docker compose build
                  docker compose push
